 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://localhost:1238/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Apr/2020 17:57:51] "[37mPOST /receive_info HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 400
For node  1 : 100
For node  2 : 0
For node  3 : 0
For node  4 : 0
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:51] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
1586185072.3317795 :: Inital block was valid, no need to resolve conflict
Average time by now None
Number of blocks 0
For node  0 : 400
For node  1 : 100
For node  2 : 0
For node  3 : 0
For node  4 : 0
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:52] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 300
For node  1 : 100
For node  2 : 100
For node  3 : 0
For node  4 : 0
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:52] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
1586185072.4256964 :: Inital block was valid, no need to resolve conflict
Average time by now None
Number of blocks 1
For node  0 : 300
For node  1 : 100
For node  2 : 100
For node  3 : 0
For node  4 : 0
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:52] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 200
For node  1 : 100
For node  2 : 100
For node  3 : 100
For node  4 : 0
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:52] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
1586185074.3656602 :: Inital block was valid, no need to resolve conflict
Average time by now None
Number of blocks 2
For node  0 : 200
For node  1 : 100
For node  2 : 100
For node  3 : 100
For node  4 : 0
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:54] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 100
For node  1 : 100
For node  2 : 100
For node  3 : 100
For node  4 : 100
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:54] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:54] "[37mPOST /start HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:54] "[37mPOST /start_client HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:54] "[37mGET /notify_start HTTP/1.1[0m" 200 -
NEW: Current Transactions not in block: 1
NEW: I have to mine the block, if this tx is valid, I have to make a new one.
1586185074.9612157 :: Inital block was valid, no need to resolve conflict
Average time by now None
Number of blocks 3
For node  0 : 100
For node  1 : 100
For node  2 : 100
For node  3 : 100
For node  4 : 100
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:54] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 100
For node  1 : 91
For node  2 : 127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
100
For node  3 : 109
For node  4 : 100
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Given input UTXO is not found in utxo records
Actually found a different chain
Average time by now None
Number of blocks 4
For node  0 : 100
For node  1 : 91
For node  2 : 100
For node  3 : 109
For node  4 : 100
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now None
Number of blocks 5
For node  0 : 100
For node  1 : 91
For node  2 : 100
For node  3 : 109
For node  4 : 100
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.5708978573481241
Number of blocks 6
For node  0 : 100
For node  1 : 91
For node  2 : 100
For node  3 : 109
For node  4 : 100
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:55] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.5406366075788226
Number of blocks 7
For node  0 : 93
For node  1 : 98
For node  2 : 100
For node  3 : 109
For node  4 : 100
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.49914386868476873
Number of blocks 8
For node  0 : 93
For node  1 : 98
For node  2 : 100
For node  3 : 114
For node  4 : 95
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4883586565653483
Number of blocks 9
For node  0 : 93
For node  1 : 98
For node  2 : 100
For node  3 : 114
For node  4 : 95
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:56] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4852975606918335
Number of blocks 10
For node  0 : 93
For node  1 : 98
For node  2 : 100
For node  3 : 114
For node  4 : 95
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
1586185077.3988705 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4606480164961381
Number of blocks 11
For node  0 : 99
For node  1 : 127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
92
For node  2 : 100
For node  3 : 127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
114
For node  4 : 95
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:57] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
Average time by now 0.472464382648468
Number of blocks 12
For node  0 : 99
For node  1 : 92
For node  2 : 100
For node  3 : 114
For node  4 : 95
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:58] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
Average time by now 0.444720066510714
Number of blocks 13
For node  0 : 99
For node  1 : 92
For node  2 : 100
For node  3 : 114
For node  4 : 95
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:58] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Average time by now 0.4299875157220023
Block mined
Number of blocks 14
For node  0 : 99
For node  1 : 92
For node  2 : 100
For node  3 : 114
For node  4 : 95
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:58] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
1586185078.4123085 :: Inital block was valid, no need to resolve conflict
Average time by now 0.40570693016052245
Number of blocks 15
For node  0 : 99
For node  1 : 92
For node  2 : 100
For node  3 : 114
For node  4 : 95
All money :  500
Average time by now 0.39169707894325256
Number of blocks 16
For node  0 : 99
For node  1 : 92
For node  2 : 100
For node  3 : 114
For node  4 : 95
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:58] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
For node  0 : 99
For node  1 : 92
For node  2 : 96
For node  3 : 114
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:58] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:58] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.40172993435579185
Number of blocks 17
For node  0 : 99
For node  1 : 92
For node  2 : 96
For node  3 : 114
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 99
For node  1 : 92
For node  2 : 96
For node  3 : 114
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:57:59] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:00] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 99
For node  1 : 92
For node  2 : 96
For node  3 : 114
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:00] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:00] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4440671337975396
Number of blocks 18
For node  0 : 99
For node  1 : 92
For node  2 : 96
For node  3 : 114
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:00] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
1586185080.647038 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4376457866869475
Number of blocks 19
For node  0 : 99
For node  1 : 92
For node  2 : 102
For node  3 : 108
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:00] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:01] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:01] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:01] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:01] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
Average time by now 0.4901219367980957
Number of blocks 20
For node  0 : 99
For node  1 : 92
For node  2 : 102
For node  3 : 108
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:02] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
Average time by now 0.47171000071934294
Number of blocks 21
For node  0 : 99
For node  1 : 92
For node  2 : 102
For node  3 : 108
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:02] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:02] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:02] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:02] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:02] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 99
For node  1 : 92
For node  2 : 102
For node  3 : 108
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mGET /request_chain HTTP/1.1[0m" 200 -
1586185083.3052526 :: Inital block was valid, no need to resolve conflict
Average time by now 0.49879454482685437
Number of blocks 22
For node  0 : 99
For node  1 : 92
For node  2 : 102
For node  3 : 108
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.5011863915816598
Number of blocks 23
For node  0 : 91
For node  1 : 92
For node  2 : 110
For node  3 : 108
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:03] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:04] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:04] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.496485730012258
Number of blocks 24
For node  0 : 91
For node  1 : 92
For node  2 : 110
For node  3 : 108
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:04] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:04] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.49432378768920904
Number of blocks 25
For node  0 : 91
For node  1 : 92
For node  2 : 110
For node  3 : 108
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:04] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
1586185085.082313 :: Inital block was valid, no need to resolve conflict
Average time by now 0.49040518357203566
Number of blocks 26
For node  0 : 91
For node  1 : 87
For node  2 : 110
For node  3 : 113
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:05] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:05] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:05] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:05] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:05] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:06] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:06] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.5152528374283403
Number of blocks 27
For node  0 : 91
For node  1 : 87
For node  2 : 110
For node  3 : 113
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:06] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:06] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
Given input UTXO is not found in utxo records
For node  0 : 91
For node  1 : 87
For node  2 : 110
For node  3 : 113
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:06] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:06] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
Average time by now 0.5143209780965533
Number of blocks 28
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 119
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:06] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:06] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.5110617012813174
Number of blocks 29
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 119
For node  4 : 99
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 111
For node  4 : 107
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.5181584914525351
Number of blocks 30
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 111
For node  4 : 107
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:07] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
1586185088.073588 :: Inital block was valid, no need to resolve conflict
Average time by now 0.5077997176877915
Number of blocks 31
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 111
For node  4 : 107
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.49570925533771526
Number of blocks 32
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 111
For node  4 : 107
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4893557086135403
Number of blocks 33
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 111
For node  4 : 107
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 111
For node  4 : 107
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
For node  0 : 91
For node  1 : 87
For node  2 : 104
For node  3 : 111
For node  4 : 107
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mPOST /new_transaction HTTP/1.1[0m" 200 -
NEW: Current Transactions not in block: 0
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mGET /request_chain HTTP/1.1[0m" 200 -
1586185088.687013 :: Inital block was valid, no need to resolve conflict
Average time by now 0.48103659994461967
Number of blocks 34
For node  0 : 104
For node  1 : 87
For node  2 : 104
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:08] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4889944212777275
Number of blocks 35
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Average time by now 0.4822644922468398
Number of blocks 36
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
Block mined
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
Average time by now 0.47418589849729803
Number of blocks 37
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mGET /request_chain HTTP/1.1[0m" 200 -
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mPOST /new_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:09] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4644940464120163
Number of blocks 38
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
NEW: Current Transactions not in block: 1
NEW: I have to mine the block, if this tx is valid, I have to make a new one.
1586185090.005166 :: Inital block was valid, no need to resolve conflict
Average time by now 0.45348475529597365
Number of blocks 39
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 97
For node  1 : 87
Block mined
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
Average time by now 0.45288661122322094
Number of blocks 40
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.44316540694818274
Number of blocks 41
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 97
For node  1 : 87
For node  2 : 111
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:10] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:11] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:11] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:11] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:11] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:11] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
127.0.0.1 - - [06/Apr/2020 17:58:11] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:12] "[37mGET /request_chain HTTP/1.1[0m" 200 -
1586185092.0487533 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4694514615195139
Number of blocks 42
For node  0 : 97
For node  1 : 88
For node  2 : 105
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:12] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:12] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:12] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:12] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:12] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:12] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:12] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4825943569804348
Number of blocks 43
For node  0 : 92
For node  1 : 88
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4793914177201012
Number of blocks 44
For node  0 : 92
For node  1 : 88
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Average time by now 0.4717287699381511
Number of blocks 45
For node  0 : 92
For node  1 : 88
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:13] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4716706224109816
Number of blocks 46
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4670920169099849
Number of blocks 47
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mPOST /new_transaction HTTP/1.1[0m" 200 -
NEW: Current Transactions not in block: 1
NEW: I have to mine the block, if this tx is valid, I have to make a new one.
Average time by now 0.4622435768445334
Number of blocks 48
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
Average time by now 0.45998005964318106
Number of blocks 49
For node  0 : 94
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mGET /request_chain HTTP/1.1[0m" 200 -
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:14] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4559531116485596
Number of blocks 50
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
1586185095.1299543 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4471221203897514
Number of blocks 51
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
Block mined
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
Average time by now 0.4428148819850042
Number of blocks 52
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 94
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 108
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:15] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mGET /request_chain HTTP/1.1[0m" 200 -
For node  0 : 127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mGET /request_chain HTTP/1.1[0m" 200 -
99
For node  1 : 86
For node  2 : 110
For node  3 : 102
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mPOST /new_transaction HTTP/1.1[0m" 200 -
1586185096.4307985 :: Inital block was valid, no need to resolve conflict
Average time by now 0.454698477151259
Number of blocks 53
For node  0 : 99
For node  1 : 86
For node  2 : 120
For node  3 : 92
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
NEW: Current Transactions not in block: 1
NEW: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:16] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.45642171524189146
Number of blocks 54
For node  0 : 99
For node  1 : 86
For node  2 : 120
For node  3 : 92
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:17] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:17] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
1586185097.5720377 :: Inital block was valid, no need to resolve conflict
Average time by now 0.45891374241222044
Number of blocks 55
127.0.0.1 - - [06/Apr/2020 17:58:17] "[37mGET /request_chain HTTP/1.1[0m" 200 -
For node  0 : 99
For node  1 : 86
For node  2 : 120
For node  3 : 92
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:17] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:17] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:17] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:17] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4587302463395256
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Number of blocks 56
For node  0 : 99
For node  1 : Successful mining and broadcast
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mGET /request_chain HTTP/1.1[0m" 200 -
86
Block mined
For node  2 : Given input UTXO is not found in utxo records
120
For node  0 : For node  3 : 99
92
For node  1 : For node  4 : 86
103
For node  2 : All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
120
For node  3 : 92
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
Average time by now 0.4520768324534099
Number of blocks 57
For node  0 : 99
For node  1 : 86
For node  2 : 120
For node  3 : 92
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4473293444205975
Number of blocks 58
For node  0 : 99
For node  1 : 86
For node  2 : 120
For node  3 : 92
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4483581437902936
Number of blocks 59
For node  0 : 99
For node  1 : 86
For node  2 : 120
For node  3 : 92
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:18] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:19] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
127.0.0.1 - - [06/Apr/2020 17:58:19] "[37mGET /request_chain HTTP/1.1[0m" 200 -
1586185099.5912313 :: Inital block was valid, no need to resolve conflict
Average time by now 0.45432419379552214
Number of blocks 60
For node  0 : 99
For node  1 : 81
For node  2 : 122
For node  3 : 92
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:19] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:19] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:19] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:19] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:19] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4612984930882689
Number of blocks 61
For node  0 : 99
For node  1 : 89
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
Block mined
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Average time by now 0.45898897417130013
Number of blocks 62
For node  0 : 99
For node  1 : 89
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:20] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Block mined
Average time by now 0.45824739289662203
Number of blocks 63
For node  0 : 99
For node  1 : 89
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:21] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
Average time by now 0.4563563615083695
Number of blocks 64
For node  0 : 99
For node  1 : 89
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:21] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Actually found a different chain
Block mined
Average time by now 0.4552362221937914
Number of blocks 65
For node  0 : 94
For node  1 : 94
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4543431238694625
Number of blocks 66
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mGET /request_chain HTTP/1.1[0m" 200 -
For node  0 : 94
For node  1 : 94
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 94
For node  1 : 94
For node  2 : 122
For node  3 : 127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mGET /request_chain HTTP/1.1[0m" 200 -
84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.45211393797575544
Number of blocks 67
For node  0 : 94
For node  1 : 94
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mGET /request_chain HTTP/1.1[0m" 200 -
For node  0 : 94
For node  1 : 94
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mPOST /new_transaction HTTP/1.1[0m" 200 -
NEW: Current Transactions not in block: 1
NEW: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:22] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 94
For node  1 : 94
Average time by now 0.4502162898288054
Block mined
Number of blocks 68
For node  2 : For node  0 : 122
94
For node  3 : For node  1 : 84
94
For node  4 : For node  2 : 106
122
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
For node  3 : Block mined
84
For node  4 : 106
All money :  500
1586185103.031474 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4449230277019999
Number of blocks 69
For node  0 : 94
For node  1 : 94
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
Average time by now 0.44111068248748786
Number of blocks 70
For node  0 : 94
For node  1 : 94
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 94
For node  1 : 94
For node  2 : 122
For node  3 : 84
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 94
For node  1 : 94
For node  2 : 131
For node  3 : 75
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:23] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 94
For node  1 : 103
For node  2 : 131
For node  3 : 75
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Given input UTXO is not found in utxo records
Actually found a different chain
Average time by now 0.4500325028325471
Number of blocks 71
For node  0 : 94
For node  1 : 103
For node  2 : 131
For node  3 : 75
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4446549978521135
Number of blocks 72
For node  0 : 94
For node  1 : 103
For node  2 : 131
For node  3 : 75
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
Average time by now 0.4393925078927654
Number of blocks 73
For node  0 : 94
For node  1 : 103
For node  2 : 131
For node  3 : 75
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:24] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:25] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:25] "[37mGET /request_chain HTTP/1.1[0m" 200 -
1586185105.4783118 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4479259606954214
Number of blocks 74
For node  0 : 94
For node  1 : 102
For node  2 : 131
For node  3 : 76
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:25] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:25] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.44532861073811847
Number of blocks 75
For node  0 : 94
For node  1 : 102
For node  2 : 131
For node  3 : 76
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:25] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:25] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:26] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:26] "[37mGET /request_chain HTTP/1.1[0m" 200 -
1586185106.5212715 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4498624644781414
Number of blocks 76
For node  0 : 94
For node  1 : 102
For node  2 : 130
For node  3 : 77
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:26] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:26] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:26] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.45465523856026785
Number of blocks 77
For node  0 : 94
For node  1 : 102
For node  2 : 130
For node  3 : 77
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
Average time by now 0.45605114790109486
Number of blocks 78
For node  0 : 94
For node  1 : 102
For node  2 : 137
For node  3 : 70
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:27] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4531415836720527
Number of blocks 79
For node  0 : 94
For node  1 : 102
For node  2 : 137
For node  3 : 70
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
Block mined
Average time by now 0.4509005039930344
Number of blocks 80
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 76
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4472204844156901
Number of blocks 81
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 76
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4432560961420943
Number of blocks 82
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 76
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.43893359655357267
Number of blocks 83
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 76
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Block mined
1586185108.82261 :: Inital block was valid, no need to resolve conflict
Average time by now 0.43441435268947054
Number of blocks 84
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 76
For node  4 : 97
All money :  500
RECEIVE  : Current Transactions not in block: 0
Given input UTXO is not found in utxo records
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 76
For node  4 : 97
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 71
For node  4 : 102
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:28] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.43629885841818417
Number of blocks 85
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 71
For node  4 : 102
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 71
For node  4 : 102
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 71
For node  4 : 102
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:29] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:30] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Given input UTXO is not found in utxo records
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:58:30] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.44389460253161056
Number of blocks 86
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 71
For node  4 : 102
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:30] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
Average time by now 0.4423920039472909
Number of blocks 87
For node  0 : 88
For node  1 : 102
For node  2 : 137
For node  3 : 71
For node  4 : 102
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:30] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:31] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:31] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:31] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:31] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:31] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:31] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:31] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:31] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:32] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
Average time by now 0.45624247735196893
Number of blocks 88
For node  0 : 88
For node  1 : 92
For node  2 : 147
For node  3 : 71
For node  4 : 102
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:32] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:32] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:32] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4569022494755434
Number of blocks 89
For node  0 : 88
For node  1 : 92
For node  2 : 147
For node  3 : 71
For node  4 : 102
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:32] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
Average time by now 0.45429055955674913
Number of blocks 90
For node  0 : 88
For node  1 : 92
For node  2 : 147
For node  3 : 69
For node  4 : 104
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4546969539516575
Number of blocks 91
For node  0 : 88
For node  1 : 92
For node  2 : 147
For node  3 : 69
For node  4 : 104
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
Given input UTXO is not found in utxo records
For node  0 : 88
For node  1 : 92
For node  2 : 147
For node  3 : 69
For node  4 : 104
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:33] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.45377143569614575
Number of blocks 92
For node  0 : 88
For node  1 : 92
For node  2 : 147
For node  3 : 69
For node  4 : 104
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
For node  0 : 88
For node  1 : 92
For node  2 : 147
For node  3 : 69
For node  4 : 104
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mPOST /new_transaction HTTP/1.1[0m" 200 -
NEW: Current Transactions not in block: 0
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4517027331936744
Number of blocks 93
For node  0 : 89
For node  1 : 92
For node  2 : 147
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Block mined
Actually found a different chain
Average time by now 0.44854134194394374
Number of blocks 94
For node  0 : 83
For node  1 : 98
For node  2 : 147
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.44748996684425757
Number of blocks 95
For node  0 : 83
For node  1 : 98
For node  2 : 147
127.0.0.1 - - [06/Apr/2020 17:58:34] "[37mGET /request_chain HTTP/1.1[0m" 200 -
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Block mined
Average time by now 0.4458697587251663
Number of blocks 96
For node  0 : 83
For node  1 : 98
For node  2 : 147
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.44198911460404544
Number of blocks 97
For node  0 : 83
For node  1 : 98
For node  2 : 147
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
1586185115.2054505 :: Inital block was valid, no need to resolve conflict
Average time by now 0.43748659990271743
Number of blocks 98
For node  0 : 83
For node  1 : 98
For node  2 : 147
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 83
For node  1 : 90
For node  2 : 155
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.43681260070415456
Number of blocks 99
For node  0 : 83
For node  1 : 90
For node  2 : 155
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:35] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:36] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 83
For node  1 : 90
For node  2 : 155
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:36] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:36] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:36] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:36] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
Given input UTXO is not found in utxo records
For node  0 : 83
For node  1 : 90
For node  2 : 155
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:36] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:36] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:36] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:37] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:37] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:37] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Given input UTXO is not found in utxo records
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4587756276130676
Number of blocks 100
For node  0 : 83
For node  1 : 90
For node  2 : 155
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
Average time by now 0.4551428922332159
Given input UTXO is not found in utxo records
Number of blocks 101
For node  0 : For node  0 : 83
83
For node  1 : For node  1 : 90
90
For node  2 : 155
For node  2 : For node  3 : 155
69
For node  3 : For node  4 : 69
103
For node  4 : All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:38] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:39] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4594800776126338
Number of blocks 102
For node  0 : 83
For node  1 : 90
For node  2 : 155
For node  3 : 69
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:39] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:39] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:39] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:39] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
127.0.0.1 - - [06/Apr/2020 17:58:39] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.46305640461375414
Number of blocks 103
For node  0 : 90
For node  1 : 90
For node  2 : 155
For node  3 : 62
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.46128764060827404
Number of blocks 104
For node  0 : 90
For node  1 : 90
For node  2 : 155
For node  3 : 62
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
For node  0 : 90
For node  1 : 90
For node  2 : 155
For node  3 : 62
For node  4 : 103
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mPOST /new_transaction HTTP/1.1[0m" 200 -
NEW: Current Transactions not in block: 0
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.45828040895007904
Number of blocks 105
For node  0 : 90
For node  1 : 90
For node  2 : 155
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 1
RECEIVE: I have to mine the block, if this tx is valid, I have to make a new one.
Block mined
1586185120.5872886 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4552404970492957
Number of blocks 106
For node  0 : 90
For node  1 : 90
For node  2 : 155
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:40] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:41] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:41] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:41] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Successful mining and broadcast
For node  0 : 99
For node  1 : 81
For node  2 : 155
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:41] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
Average time by now 0.45722583298371217
Number of blocks 107
For node  0 : 99
For node  1 : 81
For node  2 : 155
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:41] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:41] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:42] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:42] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:42] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Given input UTXO is not found in utxo records
Actually found a different chain
Average time by now 0.46718360318077934
Number of blocks 108
For node  0 : 99
For node  1 : 81
For node  2 : 155
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:42] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:42] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:43] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:43] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:43] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:43] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
Average time by now 0.4708328618915803
Number of blocks 109
For node  0 : 99
For node  1 : 85
For node  2 : 151
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:43] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:43] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:43] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:43] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4712017254395918
Number of blocks 110
For node  0 : 99
For node  1 : 85
For node  2 : 151
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
Given input UTXO is not found in utxo records
For node  0 : 99
For node  1 : 85
For node  2 : 151
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.46836641457703737
Number of blocks 111
For node  0 : 99
For node  1 : 85
For node  2 : 151
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4648167852844511
Number of blocks 112
For node  0 : 99
For node  1 : 85
For node  2 : 151
For node  3 : 67
For node  4 : 98
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:44] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
Average time by now 0.4661772483218033
Number of blocks 113
For node  0 : 99
For node  1 : 85
For node  2 : 151
For node  3 : 59
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:45] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:45] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:45] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:45] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:45] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.46677851049523605
Number of blocks 114
For node  0 : 99
For node  1 : 85
For node  2 : 151
For node  3 : 59
For node  4 : 106
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:45] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 93
For node  1 : 85
For node  2 : 151
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:45] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
Average time by now 0.46384471810382344
Number of blocks 115
For node  0 : 93
For node  1 : 85
For node  2 : 151
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:45] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:46] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:46] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:46] "[37mGET /request_chain HTTP/1.1[0m" 200 -
1586185126.7726862 :: Inital block was valid, no need to resolve conflict
Average time by now 0.46931813092067326
Number of blocks 116
For node  0 : 93
For node  1 : 85
For node  2 : 151
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:46] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
Given input UTXO is not found in utxo records
For node  0 : 93
For node  1 : 85
For node  2 : 151
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:46] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:46] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:46] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.46666523941561705
Number of blocks 117
For node  0 : 93
For node  1 : 85
For node  2 : 151
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:46] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:47] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:47] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:47] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:47] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:47] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Actually found a different chain
Average time by now 0.4688444723517208
Number of blocks 118
For node  0 : 93
For node  1 : 88
For node  2 : 148
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:47] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:47] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:48] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:48] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4731632340855959
Number of blocks 119
For node  0 : 93
For node  1 : 88
For node  2 : 148
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:48] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:48] "[37mGET /request_chain HTTP/1.1[0m" 200 -
RECEIVE  : Current Transactions not in block: 0
For node  0 : 93
For node  1 : 81
For node  2 : 155
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:48] "[37mPOST /receive_transaction HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:48] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:48] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4726268231868744
Number of blocks 120
For node  0 : 93
For node  1 : 81
For node  2 : 155
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:49] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:49] "[37mGET /request_chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:49] "[37mGET /request_chain HTTP/1.1[0m" 200 -
Average time by now 0.4758578509338631
Number of blocks 121
For node  0 : 93
For node  1 : 81
For node  2 : 155
For node  3 : 59
For node  4 : 112
All money :  500
127.0.0.1 - - [06/Apr/2020 17:58:49] "[37mPOST /receive_block HTTP/1.1[0m" 200 -
127.0.0.1 - - [06/Apr/2020 17:58:50] "[37mGET /request_chain HTTP/1.1[0m" 200 -
[2020-04-06 17:58:50,515] ERROR in app: Exception on /new_transaction [POST]
Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 224, in cli_new_transaction
    if (new_transaction(node['pub'], amount)):
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 84, in new_transaction
    ret = broadcast_transaction(t,new_id)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 29, in broadcast_transaction
    return broadcast(json_t,'receive_transaction',node_id)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 44, in broadcast
    response = requests.post('{}/{}'.format(ip,rest_point), json=json_obj)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
127.0.0.1 - - [06/Apr/2020 17:58:50] "[1m[35mPOST /new_transaction HTTP/1.1[0m" 500 -
NEW: Current Transactions not in block: 1
NEW: I have to mine the block, if this tx is valid, I have to make a new one.
Block mined
1586185130.5510333 :: Inital block was valid, no need to resolve conflict
Average time by now 0.4772068574780323
Number of blocks 122
For node  0 : 93
For node  1 : 81
For node  2 : 155
For node  3 : 59
For node  4 : 112
All money :  500
[2020-04-06 17:58:50,561] ERROR in app: Exception on /new_transaction [POST]
Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7efdf013ced0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /receive_block (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdf013ced0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 224, in cli_new_transaction
    if (new_transaction(node['pub'], amount)):
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 80, in new_transaction
    ret = State.state.mine_and_broadcast_block()
  File "/home/nikitas/Desktop/distrib/noobcash/state.py", line 93, in mine_and_broadcast_block
    if not (broadcast.broadcast_block(block)):
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 24, in broadcast_block
    return broadcast(json_block,'receive_block',node_id)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 44, in broadcast
    response = requests.post('{}/{}'.format(ip,rest_point), json=json_obj)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /receive_block (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdf013ced0>: Failed to establish a new connection: [Errno 111] Connection refused'))
127.0.0.1 - - [06/Apr/2020 17:58:50] "[1m[35mPOST /new_transaction HTTP/1.1[0m" 500 -
NEW: Current Transactions not in block: 0
Not enough UTXO coins in wallet, requested  1047 but have 112
127.0.0.1 - - [06/Apr/2020 17:58:50] "[1m[31mPOST /new_transaction HTTP/1.1[0m" 400 -
NEW: Current Transactions not in block: 0
[2020-04-06 17:58:50,590] ERROR in app: Exception on /new_transaction [POST]
Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7efdf00fcc90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /receive_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdf00fcc90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 224, in cli_new_transaction
    if (new_transaction(node['pub'], amount)):
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 84, in new_transaction
    ret = broadcast_transaction(t,new_id)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 29, in broadcast_transaction
    return broadcast(json_t,'receive_transaction',node_id)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 44, in broadcast
    response = requests.post('{}/{}'.format(ip,rest_point), json=json_obj)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /receive_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdf00fcc90>: Failed to establish a new connection: [Errno 111] Connection refused'))
127.0.0.1 - - [06/Apr/2020 17:58:50] "[1m[35mPOST /new_transaction HTTP/1.1[0m" 500 -
NEW: Current Transactions not in block: 1
NEW: I have to mine the block, if this tx is valid, I have to make a new one.
Block mined
1586185130.789582 :: Inital block was valid, no need to resolve conflict
Average time by now 0.47526648374107794
Number of blocks 123
For node  0 : 96
For node  1 : 81
For node  2 : 155
For node  3 : 59
For node  4 : 109
All money :  500
[2020-04-06 17:58:50,791] ERROR in app: Exception on /new_transaction [POST]
Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7efdf00f66d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /receive_block (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdf00f66d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 224, in cli_new_transaction
    if (new_transaction(node['pub'], amount)):
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 80, in new_transaction
    ret = State.state.mine_and_broadcast_block()
  File "/home/nikitas/Desktop/distrib/noobcash/state.py", line 93, in mine_and_broadcast_block
    if not (broadcast.broadcast_block(block)):
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 24, in broadcast_block
    return broadcast(json_block,'receive_block',node_id)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 44, in broadcast
    response = requests.post('{}/{}'.format(ip,rest_point), json=json_obj)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /receive_block (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdf00f66d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
127.0.0.1 - - [06/Apr/2020 17:58:50] "[1m[35mPOST /new_transaction HTTP/1.1[0m" 500 -
NEW: Current Transactions not in block: 0
[2020-04-06 17:58:50,808] ERROR in app: Exception on /new_transaction [POST]
Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/nikitas/anaconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7efdf013f0d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /receive_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdf013f0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 224, in cli_new_transaction
    if (new_transaction(node['pub'], amount)):
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 84, in new_transaction
    ret = broadcast_transaction(t,new_id)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 29, in broadcast_transaction
    return broadcast(json_t,'receive_transaction',node_id)
  File "/home/nikitas/Desktop/distrib/noobcash/broadcast.py", line 44, in broadcast
    response = requests.post('{}/{}'.format(ip,rest_point), json=json_obj)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/nikitas/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /receive_transaction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdf013f0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
127.0.0.1 - - [06/Apr/2020 17:58:50] "[1m[35mPOST /new_transaction HTTP/1.1[0m" 500 -
NEW: Current Transactions not in block: 1
NEW: I have to mine the block, if this tx is valid, I have to make a new one.
